//! Render bound FFI items as a zo provider binding file.
//!
//! @note — output matches the hand-written `provider/<lib>/`
//! shape: a banner, an optional `load core::c::*;`, the
//! `#link {}` block, then one `pub ffi` per binding.

use crate::model::{FfiBinding, ZoParam, ZoTy};

use zo_buffer::Buffer;

/// Renders zo provider bindings into a [`Buffer`].
pub struct Emitter {
  /// The output buffer being built.
  out: Buffer,
}

impl Emitter {
  /// Creates a new [`Emitter`].
  pub fn new() -> Self {
    Self { out: Buffer::new() }
  }

  /// Render the full `.zo` binding file for `lib`.
  pub fn render(mut self, lib: &str, bindings: &[FfiBinding]) -> String {
    self.header(lib);

    if uses_cstr(bindings) {
      self.out.str("load core::c::*;");
      self.out.newline();
      self.out.newline();
    }

    self.link(lib);

    for binding in bindings {
      self.out.newline();
      self.binding(binding);
    }

    String::from_utf8(self.out.finish()).expect("emit emits valid UTF-8")
  }

  /// Emit the "do not edit" banner.
  fn header(&mut self, lib: &str) {
    self.out.str("-! ");
    self.out.str(lib);
    self
      .out
      .str(" bindings. Generated by zo-binder — do not edit");
    self.out.newline();
    self
      .out
      .str("-! by hand; edit the shim and re-run `just bind ");
    self.out.str(lib);
    self.out.str("`.");
    self.out.newline();
    self.out.newline();
  }

  /// Emit the `#link {}` block pointing at the provider dylib.
  fn link(&mut self, lib: &str) {
    self.out.str("#link {");
    self.out.newline();

    self.out.indent();
    self.out.str("macos: \"@executable_path/libzo_provider_");
    self.out.str(lib);
    self.out.str(".dylib\",");
    self.out.newline();

    self.out.indent();
    self.out.str("linux: \"@executable_path/libzo_provider_");
    self.out.str(lib);
    self.out.str(".so\",");
    self.out.newline();

    self.out.char(b'}');
    self.out.newline();
  }

  /// Emit one `pub ffi` declaration with its doc lines.
  fn binding(&mut self, binding: &FfiBinding) {
    for line in &binding.doc {
      if line.is_empty() {
        self.out.str("-!");
      } else {
        self.out.str("-! ");
        self.out.str(line);
      }
      self.out.newline();
    }

    self.out.str("pub ffi ");
    self.out.str(&binding.name);
    self.out.char(b'(');
    self.params(&binding.params);
    self.out.char(b')');

    match &binding.ret {
      ZoTy::Unit => {}
      ret => {
        self.out.str(" -> ");
        self.write_ty(ret);
      }
    }

    self.out.char(b';');
    self.out.newline();
  }

  /// Emit a comma-separated `name: ty` parameter list.
  fn params(&mut self, params: &[ZoParam]) {
    for (index, param) in params.iter().enumerate() {
      if index > 0 {
        self.out.str(", ");
      }

      self.out.str(&param.name);
      self.out.str(": ");
      self.write_ty(&param.ty);
    }
  }

  /// Write a type's verbatim zo spelling.
  fn write_ty(&mut self, ty: &ZoTy) {
    match ty {
      ZoTy::Named(name) => self.out.str(name),
      ZoTy::Struct(name) => self.out.str(name),
      ZoTy::Unit => self.out.str("()"),
    }
  }
}

impl Default for Emitter {
  fn default() -> Self {
    Self::new()
  }
}

/// True when any binding references `CStr` (needs `core::c`).
fn uses_cstr(bindings: &[FfiBinding]) -> bool {
  bindings.iter().any(|binding| {
    is_cstr(&binding.ret)
      || binding.params.iter().any(|param| is_cstr(&param.ty))
  })
}

/// True when `ty` is the `CStr` C-string type.
fn is_cstr(ty: &ZoTy) -> bool {
  matches!(ty, ZoTy::Named("CStr"))
}
