[package]
name = "zo-driver"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:sources.
swisskit = { workspace = true }

# internal:crates.
zo-compiler = { workspace = true }
zo-reporter = { workspace = true }
zo-session = { workspace = true }

# external:crates.
clap = { workspace = true }
smol_str = { workspace = true }
