/// Inspirational quotes aligned with compilords philosophy.
pub(crate) const QUOTES: &[&str] = &[
  "\"Compile fast, analyze deep\" — i10e",
  "\"Why accept slow compilers? Just make them faster.\" — Jonathan Blow",
  "\"You have to be not afraid of your code.\" — Jonathan Blow",
  "\"The compiler that thinks while it compiles.\" — i10e",
  "\"Every core busy, every cycle counts.\" — Parallel Manifesto",
  "\"Speed is not a feature, it's the foundation.\" — i10e",
  "\"State machine is the new black.\" — i10e",
  "\"Compile at the speed of thought.\" — i10e",
  "\"Is it difficult to make a simple system.\" — Robert Virding",
  "\"Semantic is king.\" — Robert Virding",
  "\"Why accept slow compilers? Just make them faster.\" — Jonathan Blow",
  "\"DoD is about organizing your data for the transformations you want to perform.\" — Mike Acton",
  "\"Simplicity is a prerequisite for reliability.\" — Edsger W. Dijkstra",
  "\"The faster your software runs, the less power his consumed.\" — Chandler Carruth",
  "\"Re-think traditional compiler design.\" — Chandler Carruth",
  "\"Challenge assumptions with aggressive goals.\" — Chandler Carruth",
  "\"Do less work by not wasting effort.\" — Chandler Carruth",
  "\"Performance is king!\" — Mike Acton",
  "\"If you don't understand the data you don't understand the problem!\" — Mike Acton",
  "\"Conversely, understand the problem by understanding the data.\" — Mike Acton",
  "\"Different problems require different solutions.\" — Mike Acton",
  "\"Everything is a data problem. E-ve-ry-thing.\" — Mike Acton",
  "\"Solving problems you probably don't have creates more problems you definitely do.\" — Mike Acton",
  "\"Lies — software is a platform.\" — Mike Acton",
  "\"Lies — code is more important than data.\" — Mike Acton",
  "\"Performance equals Efficiency.\" — Eskil Steenberg",
  "\"I don't know why linkers are so slow, but they are slow.\" — Jonathan Blow",
  "\"People don't get it ! People don't know how fast computers are !\" — Jonathan Blow",
  "\"Simplicity is the ultimate sophistication\" — Leonardo da Vinci",
];
