[files]
extend-exclude = [
  "target/",
  "*.lock",
  "**/*.md",
  "docs/",
  "notes/",
  "apps/site/messages/",
]

[default.extend-words]
eazy = "eazy"

[default.extend-identifiers]
bitcase = "bitcase"
