[package]
name = "zor-reporter"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:sources.
swisskit = { workspace = true }

# internal:crates.

# external:crates.
anyhow = { workspace = true }
