use crate::bind::bind;
use crate::model::BindError;

/// A shim with an alias, a C string, and a void function
/// renders end to end (alias → concrete, `*const c_char` →
/// `CStr`, doc passthrough).
#[test]
fn binds_a_shim_end_to_end() {
  let src = r#"
    use std::os::raw::c_char;

    type ZoHandle = i64;

    /// Open a database.
    #[unsafe(no_mangle)]
    pub extern "C" fn db_open(path: *const c_char) -> ZoHandle { 0 }

    #[unsafe(no_mangle)]
    pub extern "C" fn db_close(handle: ZoHandle) {}
  "#;

  let expected = r#"
    -! demo bindings. Generated by zo-binder — do not edit
    -! by hand; edit the shim and re-run `just bind demo`.

    load core::c::*;

    #link {
      macos: "@executable_path/libzo_provider_demo.dylib",
      linux: "@executable_path/libzo_provider_demo.so",
    }

    -! Open a database.
    pub ffi db_open(path: CStr) -> s64;

    pub ffi db_close(handle: s64);
  "#;

  assert_eq!(bind("demo", src).unwrap(), expected);
}

/// An unsupported type fails the whole bind with its spelling.
#[test]
fn bind_rejects_unsupported_type() {
  let src = r#"
    #[unsafe(no_mangle)]
    pub extern "C" fn take(text: String) {}
  "#;

  let error = bind("demo", src).unwrap_err();

  assert_eq!(
    error,
    BindError::UnsupportedType {
      func: "take".to_string(),
      rust_ty: "String".to_string(),
    }
  );
}
