use crate::bind::bind;
use crate::model::BindError;

use indoc::indoc;

/// A shim with an alias, a C string, and a void function
/// renders end to end (alias → concrete, `*const c_char` →
/// `CStr`, doc passthrough).
#[test]
fn binds_a_shim_end_to_end() {
  let src = r#"
    use std::os::raw::c_char;

    type ZoHandle = i64;

    /// Open a database.
    #[unsafe(no_mangle)]
    pub extern "C" fn db_open(path: *const c_char) -> ZoHandle { 0 }

    #[unsafe(no_mangle)]
    pub extern "C" fn db_close(handle: ZoHandle) {}
  "#;

  let expected = indoc! {r#"
    -! demo bindings. Generated by zo-binder — do not edit
    -! by hand; edit the shim and re-run `just bind demo`.

    load core::c::*;

    #link {
      macos: "@executable_path/libzo_provider_demo.dylib",
      linux: "@executable_path/libzo_provider_demo.so",
    }

    -! Open a database.
    pub ffi db_open(path: CStr) -> s64;

    pub ffi db_close(handle: s64);
  "#};

  assert_eq!(bind("demo", src).unwrap(), expected);
}

/// An unsupported type fails the whole bind with its spelling.
#[test]
fn bind_rejects_unsupported_type() {
  let src = r#"
    #[unsafe(no_mangle)]
    pub extern "C" fn take(text: String) {}
  "#;

  let error = bind("demo", src).unwrap_err();

  assert_eq!(
    error,
    BindError::UnsupportedType {
      func: "take".to_string(),
      rust_ty: "String".to_string(),
    }
  );
}

/// The real `zo-provider-sqlite` shim generates correct
/// signatures for all four exported functions — alias
/// resolution (`ZoHandle` → `i64` → `s64`) and C-string
/// mapping (`*const c_char` → `CStr`) end to end.
///
/// @note — width-faithful: the shim returns `i64`, so the
/// binder emits `-> s64`. The hand-written `api.zo` declared
/// `-> int` (s32); `s64` is the more-correct generated form.
#[test]
fn binds_the_real_sqlite_shim() {
  let shim = include_str!("../../../zo-provider-sqlite/src/lib.rs");

  let out = bind("sqlite", shim).unwrap();

  assert!(out.contains("load core::c::*;"));
  assert!(
    out.contains("macos: \"@executable_path/libzo_provider_sqlite.dylib\",")
  );

  assert!(out.contains("pub ffi zo_sqlite_open(path: CStr) -> s64;"));
  assert!(out.contains("pub ffi zo_sqlite_close(handle: s64);"));
  assert!(
    out.contains("pub ffi zo_sqlite_exec(handle: s64, sql: CStr) -> s64;")
  );
  assert!(
    out.contains("pub ffi zo_sqlite_query_int(handle: s64, sql: CStr) -> s64;")
  );
}
