use crate::cbind::bind_c_api;
use crate::cheader::parse_c_api;
use crate::model::LinkSpec;

use indoc::indoc;

/// A system link spec for tests.
fn system_link() -> LinkSpec {
  LinkSpec::System {
    macos: "/opt/homebrew/lib/libraylib.dylib".to_string(),
    linux: "/usr/lib/x86_64-linux-gnu/libraylib.so".to_string(),
  }
}

/// A C API renders end to end: a struct definition, PascalCase
/// → snake_case names with `%% link_name`, an acronym run
/// (`GetFPS` → `get_fps`), a `(void)` param dropped, a
/// `const char *` mapped to `CStr`, and a struct return type.
#[test]
fn renders_structs_and_functions_from_c_api() {
  let json = r#"{
    "structs": [
      {
        "name": "Vector2",
        "description": "Vector2, 2 components",
        "fields": [
          { "type": "float", "name": "x", "description": "x" },
          { "type": "float", "name": "y", "description": "y" }
        ]
      }
    ],
    "enums": [],
    "aliases": [],
    "functions": [
      {
        "name": "InitWindow",
        "description": "Initialize window and OpenGL context",
        "returnType": "void",
        "params": [
          { "type": "int", "name": "width" },
          { "type": "int", "name": "height" },
          { "type": "const char *", "name": "title" }
        ]
      },
      {
        "name": "CloseWindow",
        "description": "Close window",
        "returnType": "void",
        "params": [ { "type": "void", "name": "" } ]
      },
      {
        "name": "GetFPS",
        "description": "Get current FPS",
        "returnType": "int",
        "params": []
      },
      {
        "name": "GetMousePosition",
        "description": "Get mouse position XY",
        "returnType": "Vector2",
        "params": []
      }
    ]
  }"#;

  let api = parse_c_api(json).unwrap();

  let expected = indoc! {r#"
    -! raylib bindings. Generated by zo-binder — do not edit
    -! by hand; edit the shim and re-run `just bind raylib`.

    load core::c::*;

    #link {
      macos: "/opt/homebrew/lib/libraylib.dylib",
      linux: "/usr/lib/x86_64-linux-gnu/libraylib.so",
    }

    -! Vector2, 2 components
    pub struct Vector2 {
      x: float,
      y: float,
    }

    -! Initialize window and OpenGL context
    %% link_name = "InitWindow".
    pub ffi init_window(width: int, height: int, title: CStr);

    -! Close window
    %% link_name = "CloseWindow".
    pub ffi close_window();

    -! Get current FPS
    %% link_name = "GetFPS".
    pub ffi get_fps() -> int;

    -! Get mouse position XY
    %% link_name = "GetMousePosition".
    pub ffi get_mouse_position() -> Vector2;
  "#};

  let result = bind_c_api("raylib", system_link(), &api);

  assert_eq!(result.output, expected);
  assert!(result.skipped.is_empty());
}

/// A `typedef`-style alias resolves to its target struct.
#[test]
fn resolves_aliases_to_target_structs() {
  let json = r#"{
    "structs": [
      {
        "name": "Texture",
        "description": "A texture",
        "fields": [
          { "type": "unsigned int", "name": "id", "description": "id" }
        ]
      }
    ],
    "enums": [],
    "aliases": [
      { "type": "Texture", "name": "Texture2D", "description": "alias" }
    ],
    "functions": [
      {
        "name": "LoadTextureCopy",
        "description": "Copy a texture",
        "returnType": "Texture2D",
        "params": [ { "type": "Texture2D", "name": "src" } ]
      }
    ]
  }"#;

  let api = parse_c_api(json).unwrap();
  let result = bind_c_api("raylib", system_link(), &api);

  assert!(result.skipped.is_empty());
  assert!(
    result
      .output
      .contains("pub ffi load_texture_copy(src: Texture) -> Texture;")
  );
}

/// A function with an unmappable type (a callback) is skipped,
/// not an error; supported functions still generate.
#[test]
fn skips_functions_with_unsupported_types() {
  let json = r#"{
    "structs": [],
    "enums": [],
    "aliases": [],
    "functions": [
      {
        "name": "GetFrameTime",
        "description": "Delta time",
        "returnType": "float",
        "params": []
      },
      {
        "name": "SetTraceLogCallback",
        "description": "Set logger",
        "returnType": "void",
        "params": [ { "type": "TraceLogCallback", "name": "callback" } ]
      }
    ]
  }"#;

  let api = parse_c_api(json).unwrap();
  let result = bind_c_api("raylib", system_link(), &api);

  assert!(result.output.contains("pub ffi get_frame_time() -> float;"));
  assert!(!result.output.contains("set_trace_log_callback"));
  assert_eq!(result.skipped, vec!["SetTraceLogCallback".to_string()]);
}

/// A struct that embeds a skipped struct by value is skipped
/// too, so no generated struct carries a dangling field type.
#[test]
fn skips_struct_referencing_a_skipped_struct() {
  let json = r#"{
    "structs": [
      {
        "name": "Inner",
        "description": "unmappable array field",
        "fields": [
          { "type": "float[4]", "name": "data", "description": "" }
        ]
      },
      {
        "name": "Outer",
        "description": "embeds Inner by value",
        "fields": [
          { "type": "Inner", "name": "inner", "description": "" }
        ]
      }
    ],
    "enums": [],
    "aliases": [],
    "functions": []
  }"#;

  let api = parse_c_api(json).unwrap();
  let result = bind_c_api("demo", system_link(), &api);

  assert!(!result.output.contains("struct Inner"));
  assert!(!result.output.contains("struct Outer"));
  assert_eq!(
    result.skipped,
    vec!["struct Inner".to_string(), "struct Outer".to_string()]
  );
}
