use crate::cbind::bind_c_api;
use crate::cheader::parse_c_api;
use crate::model::LinkSpec;

use indoc::indoc;

/// A C API renders end to end: a struct definition, PascalCase
/// → snake_case names with `%% link_name`, an acronym run
/// (`GetFPS` → `get_fps`), a `(void)` param dropped, a
/// `const char *` mapped to `CStr`, and a struct return type.
#[test]
fn renders_structs_and_functions_from_c_api() {
  let json = r#"{
    "structs": [
      {
        "name": "Vector2",
        "description": "Vector2, 2 components",
        "fields": [
          { "type": "float", "name": "x", "description": "x" },
          { "type": "float", "name": "y", "description": "y" }
        ]
      }
    ],
    "enums": [],
    "aliases": [],
    "functions": [
      {
        "name": "InitWindow",
        "description": "Initialize window and OpenGL context",
        "returnType": "void",
        "params": [
          { "type": "int", "name": "width" },
          { "type": "int", "name": "height" },
          { "type": "const char *", "name": "title" }
        ]
      },
      {
        "name": "CloseWindow",
        "description": "Close window",
        "returnType": "void",
        "params": [ { "type": "void", "name": "" } ]
      },
      {
        "name": "GetFPS",
        "description": "Get current FPS",
        "returnType": "int",
        "params": []
      },
      {
        "name": "GetMousePosition",
        "description": "Get mouse position XY",
        "returnType": "Vector2",
        "params": []
      }
    ]
  }"#;

  let api = parse_c_api(json).unwrap();

  let link = LinkSpec::System {
    macos: "/opt/homebrew/lib/libraylib.dylib".to_string(),
    linux: "/usr/lib/x86_64-linux-gnu/libraylib.so".to_string(),
  };

  let expected = indoc! {r#"
    -! raylib bindings. Generated by zo-binder — do not edit
    -! by hand; edit the shim and re-run `just bind raylib`.

    load core::c::*;

    #link {
      macos: "/opt/homebrew/lib/libraylib.dylib",
      linux: "/usr/lib/x86_64-linux-gnu/libraylib.so",
    }

    -! Vector2, 2 components
    pub struct Vector2 {
      x: float,
      y: float,
    }

    -! Initialize window and OpenGL context
    %% link_name = "InitWindow".
    pub ffi init_window(width: int, height: int, title: CStr);

    -! Close window
    %% link_name = "CloseWindow".
    pub ffi close_window();

    -! Get current FPS
    %% link_name = "GetFPS".
    pub ffi get_fps() -> int;

    -! Get mouse position XY
    %% link_name = "GetMousePosition".
    pub ffi get_mouse_position() -> Vector2;
  "#};

  assert_eq!(bind_c_api("raylib", link, &api).unwrap(), expected);
}
