use crate::emit::Emitter;
use crate::model::{Bindings, FfiBinding, LinkSpec, ZoParam, ZoTy};

/// A binding with no doc and no link_name (the common case).
fn binding(name: &str, params: Vec<ZoParam>, ret: ZoTy) -> FfiBinding {
  FfiBinding {
    name: name.to_string(),
    link_name: None,
    params,
    ret,
    doc: vec![],
  }
}

/// A zo-typed parameter.
fn param(name: &str, ty: ZoTy) -> ZoParam {
  ZoParam {
    name: name.to_string(),
    ty,
  }
}

/// Wrap functions in a provider [`Bindings`] (no structs).
fn provider(lib: &str, functions: Vec<FfiBinding>) -> Bindings {
  Bindings {
    lib: lib.to_string(),
    link: LinkSpec::Provider,
    structs: vec![],
    functions,
  }
}

#[test]
fn emits_scalar_bindings_without_core_c() {
  let functions = vec![
    binding("undo_stack_new", vec![], ZoTy::Named("s64")),
    binding(
      "undo_stack_push",
      vec![
        param("stack", ZoTy::Named("s64")),
        param("value", ZoTy::Named("s64")),
      ],
      ZoTy::Unit,
    ),
  ];

  let expected = r#"-! undoredo bindings. Generated by zo-binder — do not edit
-! by hand; edit the shim and re-run `just bind undoredo`.

#link {
  macos: "@executable_path/libzo_provider_undoredo.dylib",
  linux: "@executable_path/libzo_provider_undoredo.so",
}

pub ffi undo_stack_new() -> s64;

pub ffi undo_stack_push(stack: s64, value: s64);
"#;

  assert_eq!(
    Emitter::new().render(&provider("undoredo", functions)),
    expected
  );
}

#[test]
fn emits_load_core_c_and_doc_when_cstr_present() {
  let mut open = binding(
    "zo_sqlite_open",
    vec![param("path", ZoTy::Named("CStr"))],
    ZoTy::Named("int"),
  );
  open.doc = vec!["Open a connection.".to_string()];

  let functions = vec![
    open,
    binding(
      "zo_sqlite_close",
      vec![param("handle", ZoTy::Named("int"))],
      ZoTy::Unit,
    ),
  ];

  let expected = r#"-! sqlite bindings. Generated by zo-binder — do not edit
-! by hand; edit the shim and re-run `just bind sqlite`.

load core::c::*;

#link {
  macos: "@executable_path/libzo_provider_sqlite.dylib",
  linux: "@executable_path/libzo_provider_sqlite.so",
}

-! Open a connection.
pub ffi zo_sqlite_open(path: CStr) -> int;

pub ffi zo_sqlite_close(handle: int);
"#;

  assert_eq!(
    Emitter::new().render(&provider("sqlite", functions)),
    expected
  );
}

#[test]
fn blank_doc_line_has_no_trailing_space() {
  let mut item = binding("noop", vec![], ZoTy::Unit);
  item.doc = vec!["First.".to_string(), String::new(), "Third.".to_string()];

  let out = Emitter::new().render(&provider("demo", vec![item]));

  assert!(out.contains("\n-!\n"));
  assert!(!out.contains("-! \n"));
}
