[package]
name = "zo-interpreter-clif"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.
swisskit = { workspace = true }

# internal:crates.
zo-ast = { workspace = true }
zo-interner = { workspace = true }
zo-reporter = { workspace = true }
zo-session = { workspace = true }
zo-value = { workspace = true }

# external:crates.
