[package]
name = "zor"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:sources.
swisskit = { workspace = true }

# internal:crates.
zor-token = { workspace = true }
zor-tokenizer = { workspace = true }

# external:crates.
