/// Represents compiler stages that can be emitted.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Stage {
  /// The tokens generated by the tokenizer.
  Tokens,
  /// The parse tree generated by the parser.
  Tree,
  /// The semantic IR generated by the analyzer.
  Sir,
  /// The assembly code generated by the codegen.
  Asm,
  /// All outputs generated by the compiler pipeline.
  All,
}
