[package]
name = "swisskit"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.

# internal:crates.

# external:crates.
flume = { workspace = true }
Inflector = { workspace = true }
smol_str = { workspace = true }
sysinfo = { workspace = true }
