[package]
name = "zo-interpreter-zo"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.
swisskit = { workspace = true }

# internal:crates.
zo-ast = { workspace = true }
zo-interner = { workspace = true }
zo-reporter = { workspace = true }
zo-session = { workspace = true }
zo-value = { workspace = true }
zo-ty = { workspace = true }

# internal:crates.
zo-core = { workspace = true }

# external:crates.
hashbrown = { workspace = true }
smol_str = { workspace = true }
thin-vec = { workspace = true }
