[package]
name = "zor"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.
swisskit = { workspace = true }

# internal:crates.

# external:crates.
axum = { workspace = true }
flume = { workspace = true }
hashbrown = { workspace = true }
kanal = { workspace = true }
lazy_static = { workspace = true }
smol = { workspace = true }
tokio = { workspace = true }
wasmtime = { workspace = true, features = ["async"] }
