[package]
name = "zo-session"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.
swisskit = { workspace = true }

# internal:crates.
zo-interner = { workspace = true }

# external:crates.
