[package]
name = "zo-ast"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.
swisskit = { workspace = true }

# internal:crates.
zo-interner = { workspace = true }
zo-tokenizer = { workspace = true }

# external:crates.
