[package]
name = "zo"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:sources.
swisskit = { workspace = true }

# internal:crates.
zo-tokenizer = { workspace = true }
zo-tokens = { workspace = true }

# external:crates.
