[package]
name = "zo"
version.workspace = true
edition.workspace = true

[dependencies]
# internal:source.
swisskit = { workspace = true }

# internal:crates.
zo-driver = { workspace = true }

# external:crates.
futures = { workspace = true }
petgraph = { workspace = true }
rayon = { workspace = true }
tokio = { workspace = true }
