[package]
name = "zo-wasm"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# internal:source.
swisskit = { workspace = true }

# internal:crates.
zo-analyzer = { workspace = true }
zo-ast = { workspace = true }
zo-interner = { workspace = true }
zo-interpreter = { workspace = true }
zo-interpreter-zo = { workspace = true }
zo-parser = { workspace = true }
zo-reader = { workspace = true }
zo-reporter = { workspace = true }
zo-session = { workspace = true }
zo-tokenizer = { workspace = true }
zo-value = { workspace = true }

# external:crates.
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.93"
wee_alloc = "0.4.5"

[dev-dependencies]
# external:crates.
wasm-bindgen-test = "0.3.43"

[profile.release]
opt-level = "s"
